// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiQykn-TcpfkyTE3M8eavd9tU5qGI36-U',
    appId: '1:669187994051:web:428537f814e38202ab8d76',
    messagingSenderId: '669187994051',
    projectId: 'kickmybuddy-e584c',
    authDomain: 'kickmybuddy-e584c.firebaseapp.com',
    storageBucket: 'kickmybuddy-e584c.firebasestorage.app',
    measurementId: 'G-95D56WCNFG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUA7bhZUU6UhckM4ocZac5LwM9RMifFoE',
    appId: '1:669187994051:android:458bb3596c24389cab8d76',
    messagingSenderId: '669187994051',
    projectId: 'kickmybuddy-e584c',
    storageBucket: 'kickmybuddy-e584c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvMCB8pWKoS2yIcCD0dV69iQ4aB1TzVfk',
    appId: '1:669187994051:ios:89c5bfbf8fcd6c4fab8d76',
    messagingSenderId: '669187994051',
    projectId: 'kickmybuddy-e584c',
    storageBucket: 'kickmybuddy-e584c.firebasestorage.app',
    iosBundleId: 'com.example.tp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvMCB8pWKoS2yIcCD0dV69iQ4aB1TzVfk',
    appId: '1:669187994051:ios:89c5bfbf8fcd6c4fab8d76',
    messagingSenderId: '669187994051',
    projectId: 'kickmybuddy-e584c',
    storageBucket: 'kickmybuddy-e584c.firebasestorage.app',
    iosBundleId: 'com.example.tp1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiQykn-TcpfkyTE3M8eavd9tU5qGI36-U',
    appId: '1:669187994051:web:73bb946cc1c6b9afab8d76',
    messagingSenderId: '669187994051',
    projectId: 'kickmybuddy-e584c',
    authDomain: 'kickmybuddy-e584c.firebaseapp.com',
    storageBucket: 'kickmybuddy-e584c.firebasestorage.app',
    measurementId: 'G-TTXGXQ8EF5',
  );
}
